version: "3.8"

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "3000:3000"
  task-service:
    build: ./taskService
    container_name: task-service
    ports:
      - "3002:3002"
  notification-service:
    build: ./notificationService
    container_name: notification-service
    ports:
      - "3003:3003"
volumes:
  mongo_data: